- op: add
  path: /spec/template/spec/containers/0/ports
  value:
    - containerPort: 8081

- op: add
  path: /spec/template/spec/containers/0/env
  value:
    - name: REDIS_DB
      valueFrom:
        configMapKeyRef:
          name: configmap
          key: redis.db
    - name: REDIS_HOST
      valueFrom:
        configMapKeyRef:
          name: configmap
          key: redis.host
    - name: REDIS_NAME
      valueFrom:
        configMapKeyRef:
          name: configmap
          key: redis.name
    - name: REDIS_PORT
      valueFrom:
        configMapKeyRef:
          name: configmap
          key: redis.port
    - name: REDIS_PASSWORD
      valueFrom:
        secretKeyRef:
          name: web-dev-svc-redis
          key: redis-password
