- op: replace
  path: /spec/rules/0/host
  value: mailcatcher.web-dev-svc.localhost

- op: replace
  path: /spec/rules/0/http/paths/0/backend
  value:
    serviceName: web-dev-svc-mailcatcher-service
    servicePort: 1080
